# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: preinfection.Hop
PackageVersion: 0.1.5
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{8C1B6A52-4E0D-4F3B-9E62-6F0A2B7D1C11}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/preinfection/hop/releases/download/v0.1.5/HopSetup-0.1.5.exe
  InstallerSha256: 0E1B67742414FF9961B1007B110D33ABBBB2871083AFF5E8C1EEC08E59B44D36
ManifestType: installer
ManifestVersion: 1.6.0
